---
- name: add namenode dir
  file: path=/home/hadoop/namenode state=directory owner=hadoop group=hadoop

- name: Install glusterfs-fuse
  yum: name=glusterfs-fuse state=present

- template: setup hadoop mapred-site.xml
    src=mapred-site.xml.j2
    dest=/opt/hadoop/etc/hadoop/mapred-site.xml
    owner=hadoop
    group=hadoop

- template: setup hadoop slaves
    src=slaves.j2
    dest=/opt/hadoop/etc/hadoop/slaves
    owner=hadoop
    group=hadoop

- name: Mount gluster volume {{ gluster_mount_directory }}
  mount:
    name: "{{ gluster_mount_directory }}"
    src: "{{ gluster_mount_server }}:/gv0"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted

- name: Ensure Gluster brick and mount directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: hadoop
    mode: 0775
  with_items:
    - "{{ gluster_mount_directory }}"
