---
- name: This should only be run on Centos 6.x
  yum: name=xfsprogs-devel state=present

- name: Create xfs filsystem on empty gluster_install_disk
  filesystem: fstype=xfs dev={{ gluster_install_disk }}

- name: Create gluster brick directory
  file: path={{ gluster_brick_directory }} state=directory

- name: Mount XFS on gluster_brick_directory
  mount: name={{ gluster_brick_directory }} src={{ gluster_install_disk }} fstype=xfs state=mounted

- stat: path=/etc/yum.repos.d/glusterfs-epel.repo
  register: epel_repo_present

- name: Install gluster epel repo
  shell: wget -P /etc/yum.repos.d/ http://download.gluster.org/pub/gluster/glusterfs/3.6/LATEST/CentOS/glusterfs-epel.repo
  when: epel_repo_present.stat.exists == False


- name: Install glusterfs
  yum: name="glusterfs-server" state=present

- name: start gluster deamon
  service: name=glusterd state=started enabled=yes

- name: create gluster volume
  gluster_volume:
    state=present
    name=gv0
    brick={{ gluster_brick_directory }}/gv0
    rebalance=yes
    cluster="hslave1.example.com,hslave2.example.com"
  run_once: true

- name: start gluster volume
  gluster_volume: state=started name=gv0


- name: Ensure the Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_directory }}"
    src: "{{ gluster_mount_server }}:/gv0"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted

- name: Ensure Gluster brick and mount directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: hadoop
    mode: 0775
  with_items:
    - /mnt/gv0
