---

- hosts: all
  roles:
    - role: ntp
    - role: hadoop

  tasks:
  # It will be trouble if hadoop resolves the hostname to 127.0.0.1 let's remove that possibility
    - name: Remove hostname from 127.0.0.1 in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4"

- hosts: hslaves
  roles:
    - role: gluster

- hosts: hmaster
  roles:
    - role: hadoop-master
